### ISSUE TITLE
MakeI contact

### ISSUE THREAD

**Issue by Mac-Man-APH** [guisua/TimeBoard#1]
Brilliant project but as a newbie I have some questions, so how do I contact you? Sorry if this is the wrong place to do this.

Andrew

**Comment by Mac-Man-APH** [comment]
Anybody there?

**Comment by Mac-Man-APH** [comment]
The question I think is simple, how do I make the 'time' refresh when being viewed? It refreshes when you glance but not continuously.

**Comment by guisua** [comment]
Hi, 

please consider that this watch face has a 1 or 2 minute granularity. I consider refreshing the UI with every glance to be more than enough, since you don't have a second counter or any other time sensitive information. I don't really see an upside to refreshing continously.

However, I have implemented what you asked. You can checkout the branch `refresh_` for reference. This code updates the UI every 30 seconds, even if on-screen when being viewed.

Feel free to alter the timing and shorten the refresh cycle length by replacing the `30` with a smaller number of seconds. But think of battery life!

**Comment by Mac-Man-APH** [comment]
Hi Guisua

Thank you so much for replying, I didn’t know how to contact you as I don't use social media.

I am Visually Impaired and I was using the built-in X-Large watch face on my new Apple Watch which is large enough (almost too large) but I want to view more information. In the screen dump below I can 'just’ read the values on my 44mm Apple Watch but it has all the information on one watch face. The bottom left is the date and bottom right are seconds.

I found your project and it was near to what I wanted because as a self taught programer it was good place to start. This app is ONLY for my personal use but if you have any objects, I do understand and will stop. So thank you for changing your GitHub project but I couldn't find an updated version, maybe its too soon and will update tomorrow.

Regards Andrew

**Comment by guisua** [comment]
Hello Andrew!

I am excited about your ideas and would like to talk a bit more about your needs. I would love to help you develop a watch face specifically for your needs.

If you have a twitter account, drop me a direct message! I look forward to hearing from you. Https://twitter.com/guisua

**Comment by guisua** [comment]
Otherwise, just email me at g.suarez.asencio@me.com
